
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # AWS 서비스 엔드포인트
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
  mariadb:
    image: mariadb:10.6
    container_name: local-mariadb
    environment:
      - MARIA_ROOT_PASSWORD=${MARIA_ROOT_PASSWORD}
      - MARIA_DATABASE=${MARIA_DATABASE}
      - MARIA_USER=${MARIA_USER}
      - MARIA_PASSWORD=${MARIA_PASSWORD}
    ports:
      - "${MARIA_PORT}:${MARIA_PORT}"
    volumes:
      - ./tmp/mariadb-data:/var/lib/mysql
volumes:
  mariadb-data: