version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # AWS 서비스 엔드포인트
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
