// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: dispatcher/api/proto/session.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_dispatcher_api_proto_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_api_proto_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_api_proto_session_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_dispatcher_api_proto_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_api_proto_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_dispatcher_api_proto_session_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dispatcher_api_proto_session_proto protoreflect.FileDescriptor

const file_dispatcher_api_proto_session_proto_rawDesc = "" +
	"\n" +
	"\"dispatcher/api/proto/session.proto\x12\asession\"H\n" +
	"\x0eConnectRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\")\n" +
	"\rServerMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2N\n" +
	"\x0eSessionService\x12<\n" +
	"\aConnect\x12\x17.session.ConnectRequest\x1a\x16.session.ServerMessage0\x01B\x1cZ\x1adispatcher/api/proto;protob\x06proto3"

var (
	file_dispatcher_api_proto_session_proto_rawDescOnce sync.Once
	file_dispatcher_api_proto_session_proto_rawDescData []byte
)

func file_dispatcher_api_proto_session_proto_rawDescGZIP() []byte {
	file_dispatcher_api_proto_session_proto_rawDescOnce.Do(func() {
		file_dispatcher_api_proto_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dispatcher_api_proto_session_proto_rawDesc), len(file_dispatcher_api_proto_session_proto_rawDesc)))
	})
	return file_dispatcher_api_proto_session_proto_rawDescData
}

var file_dispatcher_api_proto_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dispatcher_api_proto_session_proto_goTypes = []any{
	(*ConnectRequest)(nil), // 0: session.ConnectRequest
	(*ServerMessage)(nil),  // 1: session.ServerMessage
}
var file_dispatcher_api_proto_session_proto_depIdxs = []int32{
	0, // 0: session.SessionService.Connect:input_type -> session.ConnectRequest
	1, // 1: session.SessionService.Connect:output_type -> session.ServerMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dispatcher_api_proto_session_proto_init() }
func file_dispatcher_api_proto_session_proto_init() {
	if File_dispatcher_api_proto_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dispatcher_api_proto_session_proto_rawDesc), len(file_dispatcher_api_proto_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dispatcher_api_proto_session_proto_goTypes,
		DependencyIndexes: file_dispatcher_api_proto_session_proto_depIdxs,
		MessageInfos:      file_dispatcher_api_proto_session_proto_msgTypes,
	}.Build()
	File_dispatcher_api_proto_session_proto = out.File
	file_dispatcher_api_proto_session_proto_goTypes = nil
	file_dispatcher_api_proto_session_proto_depIdxs = nil
}
