// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: linker/api/proto/push.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqUpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SqsMsgId      string                 `protobuf:"bytes,3,opt,name=sqsMsgId,proto3" json:"sqsMsgId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUpdateStatus) Reset() {
	*x = ReqUpdateStatus{}
	mi := &file_linker_api_proto_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateStatus) ProtoMessage() {}

func (x *ReqUpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_linker_api_proto_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateStatus.ProtoReflect.Descriptor instead.
func (*ReqUpdateStatus) Descriptor() ([]byte, []int) {
	return file_linker_api_proto_push_proto_rawDescGZIP(), []int{0}
}

func (x *ReqUpdateStatus) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqUpdateStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReqUpdateStatus) GetSqsMsgId() string {
	if x != nil {
		return x.SqsMsgId
	}
	return ""
}

type ResUpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         uint64                 `protobuf:"varint,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResUpdateStatus) Reset() {
	*x = ResUpdateStatus{}
	mi := &file_linker_api_proto_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResUpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResUpdateStatus) ProtoMessage() {}

func (x *ResUpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_linker_api_proto_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResUpdateStatus.ProtoReflect.Descriptor instead.
func (*ResUpdateStatus) Descriptor() ([]byte, []int) {
	return file_linker_api_proto_push_proto_rawDescGZIP(), []int{1}
}

func (x *ResUpdateStatus) GetReply() uint64 {
	if x != nil {
		return x.Reply
	}
	return 0
}

var File_linker_api_proto_push_proto protoreflect.FileDescriptor

const file_linker_api_proto_push_proto_rawDesc = "" +
	"\n" +
	"\x1blinker/api/proto/push.proto\x12\vlinker.grpc\"U\n" +
	"\x0fReqUpdateStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bsqsMsgId\x18\x03 \x01(\tR\bsqsMsgId\"'\n" +
	"\x0fResUpdateStatus\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\x04R\x05reply2\\\n" +
	"\x0eMessageService\x12J\n" +
	"\fUpdateStatus\x12\x1c.linker.grpc.ReqUpdateStatus\x1a\x1c.linker.grpc.ResUpdateStatusB\x18Z\x16linker/api/proto;protob\x06proto3"

var (
	file_linker_api_proto_push_proto_rawDescOnce sync.Once
	file_linker_api_proto_push_proto_rawDescData []byte
)

func file_linker_api_proto_push_proto_rawDescGZIP() []byte {
	file_linker_api_proto_push_proto_rawDescOnce.Do(func() {
		file_linker_api_proto_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_linker_api_proto_push_proto_rawDesc), len(file_linker_api_proto_push_proto_rawDesc)))
	})
	return file_linker_api_proto_push_proto_rawDescData
}

var file_linker_api_proto_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_linker_api_proto_push_proto_goTypes = []any{
	(*ReqUpdateStatus)(nil), // 0: linker.grpc.ReqUpdateStatus
	(*ResUpdateStatus)(nil), // 1: linker.grpc.ResUpdateStatus
}
var file_linker_api_proto_push_proto_depIdxs = []int32{
	0, // 0: linker.grpc.MessageService.UpdateStatus:input_type -> linker.grpc.ReqUpdateStatus
	1, // 1: linker.grpc.MessageService.UpdateStatus:output_type -> linker.grpc.ResUpdateStatus
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_linker_api_proto_push_proto_init() }
func file_linker_api_proto_push_proto_init() {
	if File_linker_api_proto_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_linker_api_proto_push_proto_rawDesc), len(file_linker_api_proto_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linker_api_proto_push_proto_goTypes,
		DependencyIndexes: file_linker_api_proto_push_proto_depIdxs,
		MessageInfos:      file_linker_api_proto_push_proto_msgTypes,
	}.Build()
	File_linker_api_proto_push_proto = out.File
	file_linker_api_proto_push_proto_goTypes = nil
	file_linker_api_proto_push_proto_depIdxs = nil
}
